### ISSUE TITLE
[Bot] Review ansibullbot issues and PRs

### ISSUE THREAD

**Issue by gundalow** [ansible/community#349]
Review and priorities Ansibull work that is useful for Contributor Experience:

- [ ] docs_pr https://github.com/ansible/ansibullbot/issues/1003 
- [ ] label:wip https://github.com/ansible/ansibullbot/issues/997
- [ ] Backport PRs for EOL branches https://github.com/ansible/ansibullbot/issues/929
- [ ] Comment for potential backport PR(s) https://github.com/ansible/ansibullbot/issues/951
- [ ] automerge for PRs with tests https://github.com/ansible/ansibullbot/issues/808
Document this on https://github.com/ansible/community/issues/346

**Comment by gundalow** [comment]
Document on https://etherpad.openstack.org/p/ansibot

**Comment by samccann** [comment]
We are in the process of archiving this repository.  @Andersson007 - if you think having this higher-level issue is helpful, can you open a similar issue on https://github.com/ansible/ansibullbot ?  Seems all the underlying issues are already there so will close the issue here.
