### ISSUE TITLE
Docs meeting agenda

### ISSUE THREAD

**Issue by gundalow** [ansible/community#389]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule.

Once an item has been addressed please edit the text to make it ~~strike-through~~ style (two tildes `~~` on either side of the text). 

When creating new agenda ensure docs and meeting_agenda labels are set.

Join us anytime in `#ansible-docs` on [freenode IRC](https://freenode.net/)!

**Comment by gundalow** [comment]
# 2018-10-30

## `with_` vs `loops`

* `with_` syntax is not obsolete, and is not deprecated.
* when to, and when not to use `loop` https://github.com/ansible/ansible/pull/47364#issuecomment-43147298
* https://github.com/ansible/ansible/issues/47703#issuecomment-433946762 
* **ACTION:** acozine to update the playbooks_loops page with sivel's comments

## PR Review
* Various PRs reviewed and merged

## Actions

* ~~gundalow to create backport for merged PRs~~ DONE
* acozine to rebase PR 46064
* acozine to merge https://github.com/ansible/ansible/pull/47818 (2.7 backport)
* ~~gundalow to backport https://github.com/ansible/ansible/pull/47816/files would change description of VLAN parameters~~ DONE
* acozine to update the playbooks_loops page with sivel's comments
* bizonk to alert Marketing about Docs PR 47664

# Meeting log

Minutes: https://meetbot.fedoraproject.org/ansible-docs/2018-10-30/ansible_documentation_working_group.2018-10-30-14.30.html

Log: https://meetbot.fedoraproject.org/ansible-docs/2018-10-30/ansible_documentation_working_group.2018-10-30-14.30.log.html

**Comment by acozine** [comment]
**2018-11-6**

- Better breadcrumbs proposal: https://github.com/ansible/proposals/issues/147

**Comment by acozine** [comment]
# 2018-11-13

- Better breadcrumbs proposal: https://github.com/ansible/proposals/issues/147

**Comment by acozine** [comment]
# 2018-11-20

- PR Triage - let's focus on `loop` PRs: https://github.com/ansible/ansible/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Adocs+loop+in%3Atitle
- What else? Please add YOUR topic here!

**Comment by aknrdureegaesr** [comment]
Found meeting log at https://meetbot.fedoraproject.org/ansible-docs/2018-11-20/ansible_documentation_working_group.2018-11-20-15.31.log.html and a summary at https://meetbot.fedoraproject.org/ansible-docs/2018-11-20/ansible_documentation_working_group.2018-11-20-15.31.html .

**Comment by acozine** [comment]
# 2018-11-27

- agenda fail

## Meeting log

Minutes: https://meetbot.fedoraproject.org/ansible-docs/2018-11-27/dawg_weekly.2018-11-27-15.33.html
Log: https://meetbot.fedoraproject.org/ansible-docs/2018-11-27/dawg_weekly.2018-11-27-15.33.log.html

**Comment by aknrdureegaesr** [comment]
# 2018-12-04: [#48416](https://github.com/ansible/ansible/pull/48416)

This is one random ansible contributor; @acozine [encouraged](https://github.com/ansible/ansible/pull/48416#issuecomment-442196329) me to propose my pull request [#48416](https://github.com/ansible/ansible/pull/48416) for discussion.

That PR is about improving the present not-so-helpful [module_utils docs](https://docs.ansible.com/ansible/devel/reference_appendices/module_utils.html). It does the improvement by pulling the documentation from the source. The PR also contains improvements of those source doc strings, just enough so our document-generating tool sphinx does no longer find issues.

For discussion convenience, the [improved module_utils docs](https://www.famsik.de/ansible/reference_appendices/module_utils) is available on my private server for the next few days for comparison.

**Comment by willthames** [comment]
@aknrdureegaesr I never make the meetings but I would like to say that the results of #48416 look amazing - if there's anything I can do to help the ec2 and aws.core module_utils get into the generated docs, let me know.

**Comment by jzielke84** [comment]
I would like to discuss https://github.com/ansible/ansible/issues/47844 on 12/18/2018 15:30 UTC

**Comment by dagwieers** [comment]
I would like to discuss https://github.com/ansible/ansible/issues/49970

**Comment by dagwieers** [comment]
I would like to discuss what we recommend wrt. booleans in documentation and examples.
- In the module documentation we have always used 'yes'/'no', but since recently any YAML boolean value is accepted and translated into 'yes'/'no'. (So we could be moving to yes/no values instead)
- In the module examples we always preferred using yes/no both as default value as well as in the documentation (e.g. `C(yes)`)

But YAML 1.2 moved from accepting yes/no, on/off, true/false, ... to a stricter true/false value-set, which leans to JSON boolean values. (This does not affect us as the YAML parser still accepts other values, however syntax highlighting engines do expect true/false values)

Various PRs (https://github.com/ansible/ansible/pull/50637#pullrequestreview-190217152, https://github.com/ansible/ansible/pull/48945#discussion_r238030950) introduce different boolean values in documentation (e.g. True/False)

**Comment by samccann** [comment]
# 2019-01-15

* Discuss how/where we should document how the docsite build works (autogenerated rst pages and their controlling python/jinja2 files, docsite style changes etc)

**Comment by gundalow** [comment]
The number of Working Groups continues to grow (thanks Dag), so this is making me think about https://docs.ansible.com/ansible/devel/community/communication.html#working-groups

What do people think of
1) Creating a table (or hierarchy list) based on topic (Cloud, Operating System, cross-functional) and having the groups listed under that.
2) Creating a dedicated page that simply outlines what Working Groups are and how to get involved.

**Comment by dagwieers** [comment]
Looking at that page, I don't know if an IRC channel is a necessity. Also regular meetings may not be a requirement. Both of these could mean an additional burden to something that should be as efficient as possible. A WG could get away with simply staying on top of issues and PRs, and opening issues for every perceived problem that requires attention/discussion.

To me it does require a BOTMETA $team and automatic labels in order to ensure the team gets informed, and possibly a Wiki page in order to collaborate and list priorities/ideas.

***Request for Github:** a way to notify people when a Wiki page has been edited ?*

**Comment by samccann** [comment]
# 2019-01-22
* Discuss Working Group list in docs - https://docs.ansible.com/ansible/devel/community/communication.html#working-groups

**Comment by acozine** [comment]
# 2019-01-29
* Identify docs PRs that need backporting to `stable-2.7`

## Meeting Minutes

**Comment by samccann** [comment]
# 2019-02-05

- Integrating & cross linking parts of the User Guide

    Should we mention Other Tools early so people can improve editor setup.
    Now that ansible-lint is part of the Ansible family, should we recommend this earlier on (getting started, yaml intro, fixing yaml issues)? See Reddi for details of people not knowing about ansible-lint before, and where they'd expect it to be documented

**Comment by maxwell-k** [comment]
I'd like to ask about https://github.com/ansible/ansible/pull/49798 at the next meeting ; was pointed here from #ansible-docs

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/49289 Remove old 'srtd' theme and references

**Comment by samccann** [comment]
# 2019-02-12

- Discuss [](https://github.com/ansible/ansible/pull/49798) (@maxwell-k prior comment)
- Discuss [](https://github.com/ansible/ansible/pull/49289) (@gundalow prior comment)

**Comment by samccann** [comment]
# 2019-02-19

- Discuss loop vs with_*:
    Ansible currently supports two different ways of looping over multiple items: the legacy `with_<lookup_plugin>` and the new `loop` syntax. They function slightly differently 
    Docs needs to accurately describe technical possibilities/limitations of each and provide guidance for users on when to update playbooks and when not to.
    related PRs - 47895, 47215, 47231, 47244

**Comment by acozine** [comment]
# 2019-02-26

- PR review
- Scenario Guides section, top-level TOC, and VMware Guide
- Sanity-testing docs

## Minutes
Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-02-26/ansible_dawgs.2019-02-26-15.31.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-02-26/ansible_dawgs.2019-02-26-15.31.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-02-26/ansible_dawgs.2019-02-26-15.31.log.html

**Comment by acozine** [comment]
# 2019-03-05

- Please test, fiddle with, and otherwise swarm around CSS/style issues, particularly https://github.com/ansible/ansible/issues/53071 - hoping to merge https://github.com/ansible/ansible/pull/49289 at the March 5 DaWGs meeting

**Comment by dagwieers** [comment]
We may want to discuss this and then document it:
- https://github.com/ansible/ansible/pull/53062#discussion_r262074264 -- *Creating singular parameter aliases for plural parameters (lists)*

**Comment by acozine** [comment]
# 2019-03-12

- Focus for this week is https://github.com/ansible/ansible/pull/53317 and related issues, including ansible/ansible#45651, ansible/ansible#41782, ansible/ansible#37049, ansible/ansible#28553, and for context and reference, https://github.com/ansible/proposals/issues/60. 
- Review of https://github.com/ansible/ansible/pull/53569, which addresses an idea that came out of an earlier DaWG meeting.
- Discussion of namespacing in docs examples, including https://github.com/ansible/ansible/pull/53595/files 
- Why the heck are we seeing https://github.com/ansible/ansible/issues/53665?

**Comment by acozine** [comment]
Hit the "Close and comment" button by mistake.

**Comment by samccann** [comment]
# 2019-03-19

 - Discuss version dropdown from PR #53317

## Minutes
 Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-03-19/docs_working_group_aka_dawgs.2019-03-19-15.32.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-03-19/docs_working_group_aka_dawgs.2019-03-19-15.32.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-03-19/docs_working_group_aka_dawgs.2019-03-19-15.32.log.html

**Comment by samccann** [comment]
# 2019-03-26
 - Discuss finding Module devel tips and tricks page
 - integratng ansible-lint into doc testing
 - using sphinx-rtd-theme extension for version selection dropdown

## Minutes
Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-03-26/documentation_working_group_aka_dawgs.2019-03-26-15.31.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-03-26/documentation_working_group_aka_dawgs.2019-03-26-15.31.txt
 Log: https://meetbot.fedoraproject.org/ansible-docs/2019-03-26/documentation_working_group_aka_dawgs.2019-03-26-15.31.log.html

**Comment by maxwell-k** [comment]
Could I sneak https://github.com/ansible/ansible/pull/50958 onto the agenda, last minute please?

I'm kmaxwell on IRC

**Comment by samccann** [comment]
# 2019-04-02 

- Discuss [ansible/ansible#50958 ](https://github.com/ansible/ansible/pull/50958)
- Scenario Guide PR - and waiting for redirects
- doc links embedded in code

## Meeting Minutes
- Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-04-02/ansible_documentation_working_group.2019-04-02-15.31.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-04-02/ansible_documentation_working_group.2019-04-02-15.31.txt
- Log: https://meetbot.fedoraproject.org/ansible-docs/2019-04-02/ansible_documentation_working_group.2019-04-02-15.31.log.html

**Comment by acozine** [comment]
# 2019-04-08
 - Review https://github.com/ansible/ansible/pull/54448 (potential fix for https://github.com/ansible/ansible/issues/42949)
 - Discuss requirements for custom 404 page: https://github.com/ansible/ansible/issues/51439
 - Revisit version selection issue/options/ideas for docsite:  (https://github.com/ansible/ansible/pull/53317 and https://github.com/ansible/ansible/issues/37049 and a bunch of related issues

**Comment by samccann** [comment]
# 2019-04-16
- discuss PR https://github.com/ansible/ansible/pull/54448
- discuss 404 issue https://github.com/ansible/ansible/pull/54448

## Minutes
 - Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-04-16/documentation_working_group.2019-04-16-15.30.html
- Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-04-16/documentation_working_group.2019-04-16-15.30.txt
- Log: https://meetbot.fedoraproject.org/ansible-docs/2019-04-16/documentation_working_group.2019-04-16-15.30.log.html

**Comment by samccann** [comment]
# 2019-04-23
 - Discuss speedup of doc build - pr https://github.com/ansible/ansible/pull/55593
 - How to keep the same page when switching versions - PR https://github.com/ansible/ansible/pull/53317

**Comment by acozine** [comment]
# 2019-04-30

**Meeting time moved to 30 minutes earlier! Starts at 15:00 UTC!**

 - Add agenda items here!

**Comment by acozine** [comment]
# 2019-05-06

**Meeting starts at 15:00 UTC!**

discuss https://github.com/ansible/ansible/pull/56041 (fix for https://github.com/ansible/ansible/issues/43901) - rendering of Default settings in module docs

**Comment by acozine** [comment]
# 2019-05-14

**Meeting starts at 15:00 UTC!**

Edit this comment to add agenda items here!

**Comment by samccann** [comment]
# 2019-05-21

- Discuss 2.8 release
- Tracking docsite usability issues

## Minutes
Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-05-21/ansible_documentation_working_group.2019-05-21-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-05-21/ansible_documentation_working_group.2019-05-21-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-05-21/ansible_documentation_working_group.2019-05-21-15.01.log.html

**Comment by acozine** [comment]
# 2019-05-28

- Last call for AnsibleFest proposals
- Update on version-switcher and custom 404 page
- Discussion about search capability

Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-05-28/documentation_working_group.2019-05-28-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-05-28/documentation_working_group.2019-05-28-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-05-28/documentation_working_group.2019-05-28-15.00.log.html

**Comment by acozine** [comment]
# 2019-06-04

- Breadcrumbs PR (https://github.com/ansible/ansible/pull/57316)
- Call for help with [custom 404 page](https://github.com/rtfd/sphinx-notfound-page/issues/25)
- Adopt-an-issue idea

Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-06-04/documentation_working_group_aka_dawgs.2019-06-04-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-06-04/documentation_working_group_aka_dawgs.2019-06-04-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-06-04/documentation_working_group_aka_dawgs.2019-06-04-15.00.log.html

**Comment by samccann** [comment]
# 2019-06-11

- Adopt-an-issue - easyfix docs issues https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adocs+label%3Aeasyfix+

**Comment by felixfontein** [comment]
- [ ] https://github.com/ansible/ansible/pull/57508
- [ ] https://github.com/ansible/ansible/pull/57774

**Comment by acozine** [comment]
# 2019-06-25

**Comment by acozine** [comment]
# 2019-07-02

- [ ] The docs build and Python 3 - is it time to upgrade and leave Python 2 behind? See https://github.com/ansible/ansible/pull/55986
- [ ] Add agenda items here or in another comment below

**Comment by acozine** [comment]
# 2019-07-16

- [ ] The docs build and Python 3 - is it time to upgrade and leave Python 2 behind? See https://github.com/ansible/ansible/pull/55986
- [ ] Meeting on July 9 cancelled due to internal meetings at Ansible/RH/IBM.
- [ ] Add agenda items here!!!

**Comment by acozine** [comment]
## 2019-07-23

We winged it this week.

Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-07-23/docs_working_group_aka_dawgs.2019-07-23-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-07-23/docs_working_group_aka_dawgs.2019-07-23-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-07-23/docs_working_group_aka_dawgs.2019-07-23-15.01.log.html

**Comment by samccann** [comment]
# 2019-07-30

- [ ] Discuss https://github.com/ansible/ansible/issues/51847

- [ ] Translation prep and what we need to look out for in docs

- [ ] Possible issue for community to work on  - https://github.com/ansible/ansible/issues/53520

**Comment by jamescassell** [comment]
- [ ] document 'ignore' option for group_chars https://github.com/ansible/ansible/pull/57318

**Comment by jsutton** [comment]
IRC Handle: tributarian
I would like to get clarification on what needs to be better documented in:
https://github.com/ansible/ansible/issues/12533

**Comment by samccann** [comment]
> IRC Handle: tributarian
> I would like to get clarification on what needs to be better documented in:
> [ansible/ansible#12533](https://github.com/ansible/ansible/issues/12533)

Added to the agenda and thanks!

**Comment by jsutton** [comment]
IRC Handle: tributarian
I would like to review https://github.com/ansible/ansible/pull/60492 if there is time.

**Comment by ffdybuster** [comment]
- [ ] ansible/ansible#60483

**Comment by acozine** [comment]
# 2019-08-13

- clarify documentation of command-line flags that use tags ansible/ansible#60492
- module renames in Porting Guide for 2.9 ansible/ansible#60483
- Dev Freeze for Ansible 2.9 is August 29, 2019
- Changes to tables in documentation ansible/ansible#60177 ansible/ansible#60171 and ansible/ansible#60148

Minutes: https://meetbot.fedoraproject.org/ansible-docs/2019-08-13/documentation_working_group_aka_dawgs.2019-08-13-14.31.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-docs/2019-08-13/documentation_working_group_aka_dawgs.2019-08-13-14.31.txt
Log: https://meetbot.fedoraproject.org/ansible-docs/2019-08-13/documentation_working_group_aka_dawgs.2019-08-13-14.31.log.html

**Comment by acozine** [comment]
# 2019-09-03

Add agenda items here!

**Comment by acozine** [comment]
# 2019-09-10

- [ ] add agenda items here!
- [ ] that means you, too! 
- [ ] edit this comment or add a comment of your own with items for next week's agenda

**Comment by acozine** [comment]
# 2019-09-17

- [ ] add agenda items here or in a separate comment below

**Comment by gundalow** [comment]
# Ansible Fest: Contributors Summit 

Just a reminder that Contributors Summit is happening on Monday 23rd September and will be streamed online and you can make your voice heard via IRC.

[When is this in my timezone?](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible+Contributor+Summit&iso=20190923T1250&p1=1440&ah=8&am=10)

To see what we plan to discuss see the [top level Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
From there you can see the various breakout sessions.
A lot of the morning session will be around Collections

## Call to Action!

Even if you can only make a small part of the day, or maybe can't attend at all, there are still ways take part:

* Add your thoughts, ideas and questions to the [Breakout Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
* Vote on what you'd like to be discussed (ie add `+yourname`)


## Background Reading

A large part of Monday Morning will be around "Ansible Collections", to get up to speed on what the current thoughts are, the following links will help you:

[Blog: Thoughts on restructuring the Ansible Project](https://www.ansible.com/blog/thoughts-on-restructuring-the-ansible-project)
[Blog: The future of Ansible Content Delivery](https://www.ansible.com/blog/the-future-of-ansible-content-delivery)
[Webinar: Collections and the future of how Ansible Content is handled](https://www.ansible.com/resources/webinars-training/collections-future-of-how-ansible-content-is-handled)
[Docs: Collections Tech Preview Guide](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html)

# NEW: Community Central (drop in space)

At AnsibleFest 2019 we are excited to launch Community Central, a gathering place and information hub for Ansible contributors. This takes place 10-3pm each day at AnsibeFest.

Community Central builds on the success of Ask an Expert, with a focus on contributors rather than users.

Community Central will host informal talks and coding sessions on the main conference days. Members of the Ansible Engineering team and the various Ansible Working Groups will be there.

It's a great place to discover how you can contribute to Ansible, meet other contributors, or polish your latest Ansible pull request. If you already contribute to Ansible, or would like to find out how to get involved, this is the place for you!

Feel free to come along and say hello, or even bring your laptop and we can help you through any part of the contributor or development process. Keep an eye on the Agenda Builder to see what's happening.

# Questions?

Any questions, feel free to ping me

Email: gundalow@redhat.com
Freenode: `#ansible-community`
Matrix: [ansible-community](https://matrix.to/#/#freenode_#ansible-community:matrix.org)
GitHub: @gundalow 
Twitter: @the_gundalow

**Comment by samccann** [comment]
# 2019-9-24

- Discuss filter page and options to split it up https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#62929: now that `type: list` allows `elements: xxx` for module option documentations, how about also allowing that for return value documentations? This PR implements the documentation for the crypto modules (which does't work because it is not supported), and I'd like to start a discussion whether this should be supported in the future or not.

**Comment by samccann** [comment]
# 2019-10-8

- [ ] Should we add PR links inside changelogs so users can track back to the code/docs added with the change?

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#62929: a) any idea where the `undefined label` warnings come from? b) support for `elements` in return values works.
- [ ] https://github.com/ansible/ansible/pull/63165#discussion_r331860160: question on non-text after colon

**Comment by samccann** [comment]
# 2019-10-15 

- [ ] https://github.com/ansible/ansible/pull/63486 - installing roles docs needs knowledgable reviewers

- [ ] Fix return value PRs https://github.com/ansible/ansible/pull/63478  and https://github.com/ansible/ansible/pull/63477

- [ ] https://github.com/ansible/ansible/pull/63493

- [ ] https://github.com/ansible/ansible/pull/63409 - testing first?

**Comment by samccann** [comment]
# 2019-10-22

- [ ] Docs issues triage - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

**Comment by bcoca** [comment]
https://github.com/ansible/proposals/issues/68

**Comment by samccann** [comment]
# 2019-10-29
_Please edit this comment to add agenda items for  the next DaWGs meeting_

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2019-11-12

_Please edit this comment to add agenda items for  the next DaWGs meeting_

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2019-11-19
_Please edit this comment to add agenda items for the next meeting_

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible

**Comment by xuxiaowei0512** [comment]
- [ ] ansible/ansible#63982

**Comment by samccann** [comment]
# 2019-11-26
_Please edit this comment to add agenda items for the next meeting_

- [x] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [x] Docs PRs needing reviews/merges - https://github.com/ansible/ansible

**Comment by samccann** [comment]
# 2019-12-2

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2019-12-10
_Edit this comment to add items to the meeting agenda_


- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2019-12-17
_Edit this comment to add items to the meeting agenda_


- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2020-01-07
_Edit this comment to add items to the meeting agenda_

**NOTE - No meetings Dec 24th and Dec 31**

- [ ] Status updates

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2020-01-14
_Edit this comment to add items to the meeting agenda_


- [ ] Status updates

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2020-01-21
_Edit this comment to add items to the meeting agenda_


- [ ] Status updates

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 2020-01-28
_Edit this comment to add items to the meeting agenda_


- [ ] Status updates

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ] Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by samccann** [comment]
# 02-04-2020

_edit this comment if you have agenda items to discuss at this meeting_

- [ ] Status updates

- [ ] html links extended down to the parameter level in modules and plugins - https://github.com/ansible/ansible/pull/66895

- [ ] Docs issues - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

- [ ]  Docs PRs needing reviews/merges - https://github.com/ansible/ansible/pulls?q=is%3Aopen+is%3Apr+label%3Adocs

**Comment by pilou-** [comment]
* [ ] https://github.com/ansible/ansible/issues/50278 should not role parameters be documented ?

**Comment by samccann** [comment]
Closing this Agenda/meeting minutes issue in favor of a new one for 2020. Please go to https://github.com/ansible/community/issues/521 to add to the agenda or see future meeting minutes.
(@pilou- I added your comment to next week's agenda, thanks!)
