### ISSUE TITLE
Public Ansible Project Meeting Agenda - Mar 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#450]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through.

*(Migrated from [a previous agenda](https://github.com/ansible/community/issues?q=label:core+label:meeting_agenda))*

**Comment by bcoca** [comment]
Carry overs:
- [ ] ￼ ansible/ansible#52045: add a toggle to allow unsafe group names so users can migrate from inventory scripts to inventory plugins @AlannCoding
- [ ] https://github.com/ansible/ansible/issues/52354#issue-410909935: Adopt the XDG Base Directory Specification.  My IRC name is `cedwards`. @c-edw
- [ ] lower case `choices` @nitzmahone https://github.com/ansible/community/issues/436#issuecomment-465655663
- [ ] I would like to discuss this - https://github.com/ansible/ansible/pull/32214 - irc @akasurde

**Comment by felixfontein** [comment]
Discussion point: should *_facts modules which don't return ansible_facts (re-)named to *_info? Or something else?

**Comment by samdoran** [comment]
- [ ] https://github.com/ansible/ansible/pull/53064: Add `lscpu` for gathering CPU information on Linux systems as the preferred data source, falling back to directly parsing `/proc/cpu-info`

**Comment by jamescassell** [comment]
- [ ] 2.8 CONDITIONAL_BARE_VARS deprecation warning even when value passed is a native bool -- I get a warning on every single task because they all have a conditional that's a bool... I'd assumed that the deprecation warning would only trigger when the value passed was not a native bool.

**Comment by s-hertel** [comment]
- [] https://github.com/ansible/ansible/pull/51149 Allow module_defaults set in an inner scope to be merged with those set in an outer scope. Also part of a broader conversation, allowing keywords with `extend=True` (such as `environment`) to have this behavior generally.

**Comment by abedwardsw** [comment]
- [ ] [ansible/ansible#51466](https://github.com/ansible/ansible/pull/51466#pullrequestreview-209973452): add support for regex to vars lookup plugin

**Comment by felixfontein** [comment]
- [ ] Now that we decided that we don't want `_facts` modules which do not return `ansible_facts`: how should these modules be called? `_info`? something else?

**Comment by bcoca** [comment]
Meeting ended Tue Mar  5 20:12:26 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-05/ansible_core_irc_public_meeting.2019-03-05-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-03-05/ansible_core_irc_public_meeting.2019-03-05-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-05/ansible_core_irc_public_meeting.2019-03-05-19.01.log.html

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/45805 Docs: Read arg_spec documentation from module

**Comment by jamescassell** [comment]
- [ ] https://github.com/ansible/ansible/pull/51466#issuecomment-470353478
- [ ] https://github.com/ansible/ansible/pull/53430

**Comment by drzraf** [comment]
[ ] [Gitlab service module](#40053) MR, Handles GitLab integration with [30+ external webhooks/services](https://docs.gitlab.com/ee/user/project/integrations/project_services.html)

**Comment by Xaroth** [comment]
https://github.com/ansible/ansible/pull/46687 ansible_parent_role_name/path variables for when a role is being included by another role

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#53698 specifying both an option and its alias should result in a warning (or even an error)

**Comment by ju2wheels** [comment]
#49000 and #50829 to add git-pull and git module changes

**Comment by bcoca** [comment]
Meeting ended Tue Mar 19 20:03:41 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-19/ansible_core_irc_public_meeting.2019-03-19-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-03-19/ansible_core_irc_public_meeting.2019-03-19-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-19/ansible_core_irc_public_meeting.2019-03-19-19.05.log.html

**Comment by Sajna-Shetty** [comment]
https://github.com/ansible/ansible/pull/53438 new module request

**Comment by jagadeeshnv** [comment]
https://github.com/ansible/ansible/pull/53509 new module request

**Comment by bcoca** [comment]
Meeting ended Thu Mar 21 15:37:12 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-21/ansible_core_irc_public_meeting.2019-03-21-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-03-21/ansible_core_irc_public_meeting.2019-03-21-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-21/ansible_core_irc_public_meeting.2019-03-21-15.03.log.html

**Comment by gundalow** [comment]
# Ansible 2.8.0 delay


As some of you may have noticed, Ansible-2.8.0-alpha1 has been
delayed.  It was scheduled for last week but we have one important
feature that we're still working on.  To give it a chance to be
finished up, we've slipped Alpha by two weeks (now due out on
Thursday, next week) and slipped final by one week.  

The new schedule there will be:

2019-03-28 Alpha 1 Core freeze
2019-04-04 Beta 1 Feature freeze
2019-04-18 Release Candidate 1
2019-04-25 Release Candidate 2 (if needed)
2019-04-02 Release Candidate 3 (if needed)
2019-05-09 Release

As always the `/devel/` docs contain the latest [ROADMAP](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html)

**Comment by felixfontein** [comment]
- [ ] https://github.com/ansible/ansible/pull/53698: should it announce that this will become an error eventually (concrete version)? anything else needed?

**Comment by jamescassell** [comment]
IRC: `cyberpear`

- [ ] https://github.com/ansible/ansible/pull/54272 use ANSIBLE_ prefix on all ansible-defined env vars

**Comment by bcoca** [comment]
Meeting ended Tue Mar 26 19:54:57 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-26/ansible_core_irc_public_meeting.2019-03-26-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-03-26/ansible_core_irc_public_meeting.2019-03-26-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-26/ansible_core_irc_public_meeting.2019-03-26-19.01.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Mar 28 16:06:15 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-28/ansible_core_irc_public_meeting.2019-03-28-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-03-28/ansible_core_irc_public_meeting.2019-03-28-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-28/ansible_core_irc_public_meeting.2019-03-28-15.01.log.html

**Comment by gundalow** [comment]
Agree where Plugin metadata should come from
https://github.com/ansible/ansibullbot/issues/1183#issuecomment-478001863
