### ISSUE TITLE
Public Ansible Project Meeting Agenda - Jun 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#474]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

**Comment by brtknr** [comment]
- [ ] https://github.com/ansible/ansible/pull/56710

**Comment by jamescassell** [comment]
- [ ] https://github.com/ansible/ansible/pull/57312 group chars deprecation fix

**Comment by abadger** [comment]
Also, please let me know if any of the above fixes ^ are blockers for 2.8.1 (would mean slipping 2.8.1 until next week instead of this Thursday).

**Comment by samdoran** [comment]
@abadger None of the above PRs are blockers for 2.8.1.

**Comment by jtyr** [comment]
I would like to discuss what's missing for https://github.com/ansible/ansible/pull/56817

**Comment by bcoca** [comment]
Meeting ended Thu Jun  6 15:12:08 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-06/ansible_core_irc_public_meeting.2019-06-06-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-06/ansible_core_irc_public_meeting.2019-06-06-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-06/ansible_core_irc_public_meeting.2019-06-06-15.02.log.html

**Comment by tchernomax** [comment]
- [ ] https://github.com/ansible/ansible/pull/57623 combine filter: allow merging dict and list

**Comment by dominikholler** [comment]
- [ ] ansible/ansible#57039 Handle binding:vnic_type as optional

**Comment by mattclay** [comment]
Announcement: We will continue testing the two latest versions of Fedora in our CI test matrix as we have been in the past. Our current test matrix runs the newer Fedora release with Python 3 and the older with Python 2. Going forward, both of those versions will be running Python 3.

**Comment by bcoca** [comment]
Meeting ended Tue Jun 11 19:43:20 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-11/ansible_core_irc_public_meeting.2019-06-11-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-11/ansible_core_irc_public_meeting.2019-06-11-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-11/ansible_core_irc_public_meeting.2019-06-11-19.00.log.html

**Comment by bcoca** [comment]
- [ ] https://github.com/ansible/ansible/issues/57138 more specific visual output on failed playbooks

**Comment by bcoca** [comment]
Meeting ended Thu Jun 13 15:58:41 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-13/ansible_core_irc_public_meeting.2019-06-13-15.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-13/ansible_core_irc_public_meeting.2019-06-13-15.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-13/ansible_core_irc_public_meeting.2019-06-13-15.04.log.html

**Comment by tchernomax** [comment]
- [ ] https://github.com/ansible/ansible/pull/57915 wait_for_connection: allow test with raw module (if community meeting is a place where PR can be review)

**Comment by bcoca** [comment]
Meeting ended Tue Jun 18 19:56:44 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-18/ansible_core_irc_public_meeting.2019-06-18-19.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-18/ansible_core_irc_public_meeting.2019-06-18-19.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-18/ansible_core_irc_public_meeting.2019-06-18-19.04.log.html

**Comment by lhoss** [comment]
* [ ] ansible/ansible#23738 : overwrite option to include_vars 
  * [ ] (opt) discuss other/better(?) solutions for https://github.com/ansible/proposals/pull/21#issuecomment-503569642 ( "Load included role vars files from defaults folder")

**Comment by bcoca** [comment]
Meeting ended Thu Jun 20 16:04:22 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-20/ansible_core_irc_plublic_meeting.2019-06-20-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-20/ansible_core_irc_plublic_meeting.2019-06-20-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-20/ansible_core_irc_plublic_meeting.2019-06-20-15.03.log.html

**Comment by felixfontein** [comment]
- [ ] question: how to proceed with `_facts` (or other) modules which return `ansible_facts`, but are doing so wrongfully? Rename them (for `_facts` modules), deprecate `ansible_facts` results (also see second point)? Or deprecate the module and create a new one (for `_facts` modules)?
- [ ] general: do we want to be able to deprecate return values? (In a way which informs users about this, like deprecation notices for modules.) If yes, how could that look like?

**Comment by nitzmahone** [comment]
- [ ] question: should looped calls to `ansible_facts` modules merge the results (consistent with repeated standalone calls) or return the last `ansible_facts` dict verbatim? Answer will direct the fix for #56234...

**Comment by bcoca** [comment]
Meeting ended Tue Jun 25 19:42:00 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-25/ansible_core_irc_public_meeting.2019-06-25-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-25/ansible_core_irc_public_meeting.2019-06-25-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-25/ansible_core_irc_public_meeting.2019-06-25-19.02.log.html

**Comment by jamescassell** [comment]
- [ ] are there any plans to move all community supported modules out of ansible proper?  (such as into their own collection?)  (getting some FUD that we should use only core-maintained modules for support reasons, and community modules will go away)

**Comment by bcoca** [comment]
Meeting ended Thu Jun 27 16:05:05 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-27/ansible_core_irc_public_meeting.2019-06-27-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-06-27/ansible_core_irc_public_meeting.2019-06-27-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-06-27/ansible_core_irc_public_meeting.2019-06-27-15.03.log.html
