### ISSUE TITLE
Public Ansible Project Meeting Agenda - Aug 2019

### ISSUE THREAD

**Issue by bcoca** [ansible/community#482]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by jamescassell** [comment]
- [ ] https://github.com/ansible/ansible/pull/59823 vfat selinux issue

**Comment by jborean93** [comment]
I probably won't be there to discuss it but we should get a consensus on how the move to argparse for our cli tools means the verbosity option can only be set in 1 location when using sub parsers (`ansible-galaxy`, `ansible-vault`). In the current implementation the verbosity option is set per action so needs to come after the action, e.g. `ansible-galaxy -v install` silently ignores the level while `ansible-galaxy install -v` sets the verbosity level to 1.

The alternative can be done but means `ansible-galaxy install -v` will now fail instead of silently ignoring the option;

```
ansible-galaxy install -v
usage: ansible-galaxy [-h] [--version] [-v] TYPE ...
ansible-galaxy: error: unrecognized arguments: -v
```

I've been unable to find a way to preserve the pre 2.9 behaviour where both ways work so unless someone has an idea we need to choose what way to go forward.

https://github.com/ansible/ansible/pull/59957 changes `ansible-galaxy` to have `-v` as an arg for the base parser and not per action e.g. `ansible-galaxy -v install` but that can be changed. Other clis like `ansible-playbook` should be unaffected as they don't use sub parsers.

Whatever we choose should also be reflected in the porting guide for 2.9.

cc @sivel

**Comment by felixfontein** [comment]
There are 114 `_facts` modules which return `ansible_facts`, but should be `_info` modules (https://gist.github.com/felixfontein/a6a1be999698da0ab3bd8868de6f16e1 - I excluded all modules in `networks/`, and hope I removed all which should actually be `_facts` modules). We discussed earler (https://github.com/ansible/community/issues/474#issuecomment-504782354, https://meetbot.fedoraproject.org/ansible-meeting/2019-06-25/ansible_core_irc_public_meeting.2019-06-25-19.02.log.html) that renaming and deprecating the return values would be best, but now it looks like support for deprecating return values (https://github.com/ansible/ansible/projects/34#card-22149177) won't make it into 2.9. We can now do:

  (a) Deprecate these `_facts` modules and create a new `_info` module for each of them;
  (b) Rename them, and make them programatically return `ansible_facts` when called as `xxx_facts`, or not `ansible_facts` when called as `xxx_info`, with a deprecation warning when `xxx_facts` is called;
  (c) Rename them, make them return both `ansible_facts` and the same results outside `ansible_facts`, and warn in the documentation that the `ansible_facts` results will be deprecated and removed in 2.13 (there will be no warning when these facts will be used - that might change in 2.10, though).

We should decide which of these options (or additional ones?) we want to use / suggest to maintainers. (IMO we should have one default we prefer, and possibly (a) as an alternative in case we didn't decide for (a).) Once we have this, I'll create issues for all these modules so that maintainers can decide what they prefer.

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#59060 more module validation

**Comment by jillr** [comment]
Meeting ended Tue Aug  6 20:08:40 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-06/ansible_core_public_irc_meeting.2019-08-06-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-08-06/ansible_core_public_irc_meeting.2019-08-06-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-06/ansible_core_public_irc_meeting.2019-08-06-19.02.log.html

**Comment by felixfontein** [comment]
- [ ] implemented (b) from above in ansible/ansible#60178

**Comment by s-hertel** [comment]
Meeting ended Thu Aug  8 16:53:14 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-08/ansible_core_2019-08-08.2019-08-08-15.48.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-08-08/ansible_core_2019-08-08.2019-08-08-15.48.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-08/ansible_core_2019-08-08.2019-08-08-15.48.log.html

**Comment by jillr** [comment]
Meeting ended Tue Aug 13 19:57:04 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-13/ansible_core_public_irc_meeting.2019-08-13-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-08-13/ansible_core_public_irc_meeting.2019-08-13-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-13/ansible_core_public_irc_meeting.2019-08-13-19.00.log.html

**Comment by resmo** [comment]
* [ ] https://github.com/ansible/ansible/pull/56549
* [ ] https://github.com/ansible/ansible/pull/57266
* [ ] https://github.com/ansible/ansible/pull/60527

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/60222 Add filters to os_router and os_subnet 

Backport policy

**Comment by Timoses** [comment]
- [ ]  https://github.com/ansible/ansible/pull/60593 New vars plugin: `recursive_group_vars`

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#60736 Hint at `ansible_python_interpreter` in `missing_required_lib`

**Comment by resmo** [comment]
- [ ] https://github.com/ansible/ansible/issues/60833

**Comment by jillr** [comment]
Meeting ended Tue Aug 20 20:00:12 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-20/ansible_core_irc_meeting.2019-08-20-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-08-20/ansible_core_irc_meeting.2019-08-20-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-08-20/ansible_core_irc_meeting.2019-08-20-19.01.log.html

**Comment by ju2wheels** [comment]
- [ ] [] #4900 git: add explicit submodule_init parameter, add submodule_depth parameter, and cleanup parameter support verification.

**Comment by jborean93** [comment]
- [ ] https://github.com/ansible/ansible/pull/61295 - Whether this should be done for Python or just PowerShell. Will cause a slight behaviour change but I argue it's a better change.

**Comment by felixfontein** [comment]
_facts → _info rename PRs with no reaction from maintainers (neither in issue nor in PR):
- [ ] oVirt: ansible/ansible#61299
- [ ] OneView: ansible/ansible#61208
- [ ] Scaleway: ansible/ansible#61095
- [ ] Online: ansible/ansible#61091
- [ ] smartos_image_facts: ansible/ansible#60915
- [ ] vertica_facts: ansible/ansible#60916
