### ISSUE TITLE
Public Ansible Project Meeting Agenda - Sept 2019

### ISSUE THREAD

**Issue by jillr** [ansible/community#486]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/53595 Prefer ansible_facts namespace in examples
How do we want to proceed?

**Comment by jillr** [comment]
2019-09-03 meeting effectively cancelled, low turnout.
Meeting ended Tue Sep  3 19:16:51 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-09-03/ansible_core_irc_meeting.2019-09-03-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-09-03/ansible_core_irc_meeting.2019-09-03-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-09-03/ansible_core_irc_meeting.2019-09-03-19.02.log.html

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/61828 docs_fragment guideline

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#61659
- [ ] ansible/ansible#61964; Q: what is the expected behavior?

**Comment by jillr** [comment]
Meeting ended Tue Sep 10 20:01:11 2019 UTC. Information about MeetBot at 
http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2019-09-10/ansible_core_irc_public_meeting.2019-09-10-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2019-09-10/ansible_core_irc_public_meeting.2019-09-10-19.00.txt
13:01 <@zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-09-10/ansible_core_irc_public_meeting.2019-09-10-19.00.log.html

**Comment by gundalow** [comment]
# Ansible Fest: Contributors Summit 

Just a reminder that Contributors Summit is happening on Monday 23rd September and will be streamed online and you can make your voice heard via IRC.

[When is this in my timezone?](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible+Contributor+Summit&iso=20190923T1250&p1=1440&ah=8&am=10)

To see what we plan to discuss see the [top level Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
From there you can see the various breakout sessions.
A lot of the morning session will be around Collections

## Call to Action!

Even if you can only make a small part of the day, or maybe can't attend at all, there are still ways take part:

* Add your thoughts, ideas and questions to the [Breakout Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
* Vote on what you'd like to be discussed (ie add `+yourname`)


## Background Reading

A large part of Monday Morning will be around "Ansible Collections", to get up to speed on what the current thoughts are, the following links will help you:

[Blog: Thoughts on restructuring the Ansible Project](https://www.ansible.com/blog/thoughts-on-restructuring-the-ansible-project)
[Blog: The future of Ansible Content Delivery](https://www.ansible.com/blog/the-future-of-ansible-content-delivery)
[Webinar: Collections and the future of how Ansible Content is handled](https://www.ansible.com/resources/webinars-training/collections-future-of-how-ansible-content-is-handled)
[Docs: Collections Tech Preview Guide](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html)

# NEW: Community Central (drop in space)

At AnsibleFest 2019 we are excited to launch Community Central, a gathering place and information hub for Ansible contributors. This takes place 10-3pm each day at AnsibeFest.

Community Central builds on the success of Ask an Expert, with a focus on contributors rather than users.

Community Central will host informal talks and coding sessions on the main conference days. Members of the Ansible Engineering team and the various Ansible Working Groups will be there.

It's a great place to discover how you can contribute to Ansible, meet other contributors, or polish your latest Ansible pull request. If you already contribute to Ansible, or would like to find out how to get involved, this is the place for you!

Feel free to come along and say hello, or even bring your laptop and we can help you through any part of the contributor or development process. Keep an eye on the Agenda Builder to see what's happening.

# Questions?

Any questions, feel free to ping me

Email: gundalow@redhat.com
Freenode: `#ansible-community`
Matrix: [ansible-community](https://matrix.to/#/#freenode_#ansible-community:matrix.org)
GitHub: @gundalow 
Twitter: @the_gundalow

**Comment by akors** [comment]
-  [ ]  https://github.com/ansible/ansible/pull/58323 Fix for issue ansible/ansible#58284

**Comment by jillr** [comment]
Meeting ended Tue Sep 17 19:54:00 2019 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes:  https://meetbot.fedoraproject.org/ansible-meeting/2019-09-17/ansible_core_irc_public_meeting.2019-09-17-19.01.html
Minutes (text):  https://meetbot.fedoraproject.org/ansible-meeting/2019-09-17/ansible_core_irc_public_meeting.2019-09-17-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2019-09-17/ansible_core_irc_public_meeting.2019-09-17-19.01.log.html

**Comment by nre-ableton** [comment]
- [ ] https://github.com/ansible/ansible/pull/28552:  vmware: Only add configured network interfaces to facts

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#62719: does it make sense to add more module default groups? and if yes, what to do about exceptions (i.e. modules from that group which shouldn't be in the default group)?

**Comment by nkakouros** [comment]
- [ ] [ansible/propopals#171](https://github.com/ansible/proposals/issues/171)  Intelligent role defaults resolution

**Comment by jamescassell** [comment]
- [ ] https://github.com/ansible/ansible/pull/59958
- [ ] I was removed from ansible-lockdown repo because "You were removed from Ansible organization because you do not have two-factor authentication enabled." I've since enable 2FA.  Please re-add me to ansible-lockdown repo. (also, would be good to send a notice to folks who will be removed ahead of time, and/or auto re-add once they've enabled 2FA.)
