### ISSUE TITLE
Public Ansible Project Meeting Agenda - January 2020

### ISSUE THREAD

**Issue by samdoran** [ansible/community#516]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-through/check mark.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by samdoran** [comment]
Moving over items from #507 

From @jtyr:
- [ ] ansible/ansible#62662
- [ ] ansible/ansible#65799
- [ ] ansible/ansible#65801

From @Akasurde:
- [ ] ansible/ansible#57574

**Comment by bcoca** [comment]
Meeting ended Tue Jan  7 19:55:32 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-07/ansible_core_irc_public_meeting.2020-01-07-19.15.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-01-07/ansible_core_irc_public_meeting.2020-01-07-19.15.txt

**Comment by bcoca** [comment]
Meeting ended Thu Jan  9 15:54:26 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-09/ansible_core_public_irc_meeting.2020-01-09-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-01-09/ansible_core_public_irc_meeting.2020-01-09-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-09/ansible_core_public_irc_meeting.2020-01-09-15.01.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#65745
- [ ] ansible/ansible#65747

**Comment by tremble** [comment]
- [ ] ansible/ansible#66385 - Add sanity test to ensure 'elements' documentation matches argument_spec
- [ ] ansible/ansible#66386 - Add sanity test to **require** 'elements' when type='list'

Both of these add quite a few lines to the sanity ignore.txt, but ensuring elements is defined and documented significantly improves the documentation.

**Comment by jamescassell** [comment]
- [ ] https://github.com/ansible/ansible/pull/64341 unique filter regression fixes

**Comment by jillr** [comment]
Meeting ended Tue Jan 21 20:02:59 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-21/ansible_core_irc_public_meeting.2020-01-21-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-01-21/ansible_core_irc_public_meeting.2020-01-21-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-21/ansible_core_irc_public_meeting.2020-01-21-19.00.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#66389 clean up `FILE_COMMON_ARGUMENTS`

**Comment by jtyr** [comment]
I would like to discuss the following PRs today:

- [ ]  ansible/ansible#62662
- [ ]  ansible/ansible#65799
- [ ]  ansible/ansible#65801

**Comment by samdoran** [comment]
Meeting ended Thu Jan 23 16:03:04 2020 UTC
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-23/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues516.2020-01-23-15.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-01-23/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues516.2020-01-23-15.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-23/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues516.2020-01-23-15.04.log.html

**Comment by jillr** [comment]
Meeting ended Tue Jan 28 19:47:33 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-28/ansible_core_irc_public_meeting.2020-01-28-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-01-28/ansible_core_irc_public_meeting.2020-01-28-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-01-28/ansible_core_irc_public_meeting.2020-01-28-19.02.log.html
