### ISSUE TITLE
Public Ansible Project Meeting Agenda - February 2020

### ISSUE THREAD

**Issue by samdoran** [ansible/community#519]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by samdoran** [comment]
Bringing over topics from #516 

@felixfontein:
- [ ] ansible/ansible#66389 clean up `FILE_COMMON_ARGUMENTS`

**Comment by pdumais** [comment]
I'd like to bring up the subject discussed in  #66582 (adding v2_playbook_on_task_end in CallbackModule).

**Comment by felixfontein** [comment]
- [ ] how should deprecation version number mismatches be handled in the future (especially with collections)? ansible/ansible#66920
- more sanity checks:
  - [ ] ansible/ansible#66921
  - [ ] ansible/ansible#66965
  - [ ] ansible/ansible#66961

**Comment by jillr** [comment]
Meeting ended Tue Feb  4 20:13:10 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-04/ansible_core_irc_public_meeting.2020-02-04-19.06.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-02-04/ansible_core_irc_public_meeting.2020-02-04-19.06.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-04/ansible_core_irc_public_meeting.2020-02-04-19.06.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#67243 `add_file_common_arguments`: fix defaults and tpyes, improve sanity checking

**Comment by felixfontein** [comment]
While I'm at it, one more :)

- [ ] ansible/ansible#61659

**Comment by tremble** [comment]
[ ] https://github.com/ansible/ansible/pull/67281 - Should we change AWSRetry's default behaviour to *not* catching NotFound errors

**Comment by jillr** [comment]
Meeting ended Tue Feb 11 20:02:48 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-11/ansible_core_irc_public_meeting.2020-02-11-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-02-11/ansible_core_irc_public_meeting.2020-02-11-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-11/ansible_core_irc_public_meeting.2020-02-11-19.00.log.html

**Comment by pilou-** [comment]
* [ ] https://github.com/ansible/ansible/issues/50278

    Following previous documentation meetings [older](https://meetbot.fedoraproject.org/ansible-docs/2019-01-15/docs_working_group.2019-01-15-15.30.log.html#l-47), [newer](https://meetbot.fedoraproject.org/ansible-docs/2020-02-11/dawgs_(documentation_working_group).2020-02-11-14.32.html), what is the expected behavior ? _role params would bleed, role vars: should not_ or the current one ?

Once behavior has been decided, documentation could be improved:

  * scope of role params isn't documented, role params are only mentioned in the [precedence list](https://docs.ansible.com/ansible/devel/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)
  * scope of variables defined in `defaults`  directory is mentioned [here](https://docs.ansible.com/ansible/devel/user_guide/playbooks_variables.html#id15) but the scope of variables defined in `vars` directory isn't mentioned here (it is mentioned in [import_role documentation](https://docs.ansible.com/ansible/devel/modules/import_role_module.html#notes)).
  * The documentation doesn't state that the variables defined with `vars` keyword below `role:` behave like variables defined in `roels/<rolename>vars` directory.
  * Is there any reason to use role variables instead of role parameters in the [examples](https://docs.ansible.com/ansible/devel/user_guide/playbooks_reuse_roles.html) with `role:` ?
  * `import_role` doesn't allow to use role parameters: hence every `role:` keyword can not be replaced by `import_role`. However the current documentation states:
    * [that](https://docs.ansible.com/ansible/devel/user_guide/playbooks_reuse_roles.html#importing-roles-static-re-use):
        > You can re-use roles statically anywhere in the tasks section of a play using import_role. The behavior is the same as using the roles keyword.
    * [`import_role` doc](https://docs.ansible.com/ansible/devel/modules/import_role_module.html#synopsis)
        > Much like the roles: keyword
  * [Scoping documentation](https://docs.ansible.com/ansible/devel/user_guide/playbooks_variables.html#scoping-variables) is sparse:
    > Play: each play and contained structures, vars entries (vars; vars_files; vars_prompt), role defaults and vars.

    `vars entries` isn't well defined (is the `vars` keyword of a task a `vars entries` ?)
  * [`vars` keyword documentation](https://docs.ansible.com/ansible/devel/reference_appendices/playbooks_keywords.html#term-133) doesn't mention that scope of `import_role: vars` differs from the scope of any other variables defined using `vars` keywords and another task.

**Comment by samdoran** [comment]
Meeting ended Thu Feb 13 16:43:06 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-13/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues519.2020-02-13-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-02-13/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues519.2020-02-13-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-13/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues519.2020-02-13-15.01.log.html

**Comment by jillr** [comment]
Meeting ended Tue Feb 18 19:47:29 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-18/ansible_core_irc_public_meeting.2020-02-18-19.08.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-02-18/ansible_core_irc_public_meeting.2020-02-18-19.08.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-18/ansible_core_irc_public_meeting.2020-02-18-19.08.log.html

**Comment by gundalow** [comment]
## Ansible Contributors Summit EUROPE

## What

Ansible Contributor Summit is a one day event especially for community contributors to meet with each other, as well as Ansible development teams (Core, AWX/Tower, Galaxy) in person, to discuss important issues in the community and help shape the future of Ansible. For those unable to make it to Gothenburg, we welcome you to join virtually for part/all of the day. Online participation and streaming details to follow closer to the summit.

## When
* Contributors Summit: Sunday, 29th March
* Ansible Hackathon: Monday 30th March
* [FOSS-North](https://foss-north.se/2020/): 30 & 31st March

## How

* If you plan to attend **in person**, please register on [Eventbrite](https://www.eventbrite.com/e/ansible-contributor-summit-eu-registration-92039844653)
* If you plan to attend the hackathon or any of FOSS-North please [register](https://foss-north.se/2020/)
* If you plan to attend virtually details will be added to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020) the day before

## Agenda

* Please add suggested topics to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020)
For more info please see the [announcement](https://groups.google.com/forum/#!topic/ansible-devel/o6xnI9g8QqM).

**Comment by jillr** [comment]
No attendees today.
Meeting ended Tue Feb 25 19:09:54 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-25/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues519.2020-02-25-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-02-25/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues519.2020-02-25-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-02-25/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues519.2020-02-25-19.01.log.html

**Comment by giner** [comment]
[ ] Playbooks: Inventory variables should override playbook lever variables by default, see https://github.com/ansible/ansible/issues/63668
[ ] hosts: reference parent groups from children (makes copy/pastes easy)
