### ISSUE TITLE
Public Ansible Project Meeting Agenda - March 2020

### ISSUE THREAD

**Issue by jillr** [ansible/community#528]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by jillr** [comment]
Agenda item carried over from #519 @giner 
- [ ]  Playbooks: Inventory variables should override playbook lever variables by default, see https://github.com/ansible/ansible/issues/63668
- [ ] Hosts: reference parent groups from children (makes copy/pastes easy)

**Comment by jillr** [comment]
Meeting ended Tue Mar  3 19:15:11 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-03/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-03-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-03-03/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-03-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-03/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-03-19.01.log.html

**Comment by Akasurde** [comment]
- [ ] https://github.com/ansible/ansible/pull/65869 Can someone please review this? Ping @patrakov and @Akasurde

**Comment by jillr** [comment]
Meeting ended Tue Mar 10 19:17:03 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-10/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-10-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-03-10/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-10-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-10/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-10-19.00.log.html

**Comment by bcoca** [comment]
[ ] Trying to make final decision on https://github.com/ansible/ansible/pull/66650

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#68177 Allow to deprecate options and aliases by date, and related to that:
- [ ] ansible/ansible#66920 Add/enable tests which fail when deprecation deadline is exceeded

**Comment by jillr** [comment]
Meeting ended Tue Mar 17 19:55:41 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-17/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-17-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-03-17/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-17-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-17/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-17-19.01.log.html

**Comment by jillr** [comment]
@giner - if you are able to attend a meeting in the future, please add your agenda items at that time and let us know what your irc nick is.

**Comment by jillr** [comment]
Meeting ended Tue Mar 24 19:50:02 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-24/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-24-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-03-24/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-24-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-24/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-24-19.01.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Mar 26 15:51:48 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-26/ansible_core_public_irc_meeting.2020-03-26-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-03-26/ansible_core_public_irc_meeting.2020-03-26-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-26/ansible_core_public_irc_meeting.2020-03-26-15.03.log.html

**Comment by jillr** [comment]
No topics discussed today.
Meeting ended Tue Mar 31 19:11:01 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-31/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-31-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-03-31/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-31-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-03-31/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues528.2020-03-31-19.02.log.html
