### ISSUE TITLE
Public Ansible Project Meeting Agenda - May 2020

### ISSUE THREAD

**Issue by bcoca** [ansible/community#536]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by bcoca** [comment]
From april and @tremble  https://github.com/ansible/community/issues/532#issuecomment-620172358
- [x] https://github.com/ansible/ansible/issues/69190 - behaviour of the various 'Required' options in AnsibleModule

**Comment by bcoca** [comment]
Meeting ended Tue May  5 20:09:25 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-05/ansible_core_public_irc_meeting.2020-05-05-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-05/ansible_core_public_irc_meeting.2020-05-05-19.05.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-05/ansible_core_public_irc_meeting.2020-05-05-19.05.log.html

**Comment by bcoca** [comment]
Meeting ended Thu May  7 15:03:57 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-07/ansible_core_public_irc_meeting.2020-05-07-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-07/ansible_core_public_irc_meeting.2020-05-07-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-07/ansible_core_public_irc_meeting.2020-05-07-15.00.log.html

**Comment by bcoca** [comment]
[ ] https://github.com/ansible/ansible/pull/69087  accept unvault lookup in base? (possibly a vault one also?)
 [ ] https://github.com/bcoca/collection/issues/3 new home for cannonical collection layout? (not example nor commented, though we should have those too)

**Comment by ericsysmin** [comment]
> [ ] [ansible/ansible#69087](https://github.com/ansible/ansible/pull/69087) accept unvault lookup in base? (possibly a vault one also?)
> [ ] [bcoca/collection#3](https://github.com/bcoca/collection/issues/3) new home for cannonical collection layout? (not example nor commented, though we should have those too)

I was introduced to https://github.com/ansible-community/protogen by @ssbarnea is it possible we can use this with that canonical collection layout to help promote proper testing?

**Comment by bcoca** [comment]
diff things, that is 'collection repo', while the repo above just reflects 'pure collection structure reference'

**Comment by ericsysmin** [comment]
Got it.

**Comment by bcoca** [comment]
[ ] https://github.com/ansible/ansible/pull/66650

**Comment by s-hertel** [comment]
Meeting ended Tue May 12 19:41:50 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
15:41 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-12/ansible_core_public_irc_meeting.2020-05-12-19.03.html
15:41 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-12/ansible_core_public_irc_meeting.2020-05-12-19.03.txt
15:41 Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-12/ansible_core_public_irc_meeting.2020-05-12-19.03.log.html

**Comment by bcoca** [comment]
Meeting ended Thu May 14 15:36:29 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-14/ansible_core_public_irc_meeting.2020-05-14-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-14/ansible_core_public_irc_meeting.2020-05-14-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-14/ansible_core_public_irc_meeting.2020-05-14-15.01.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69291 ansible-test: allow version_added tests for collections

**Comment by jamescassell** [comment]
- [ ] missing Proposal for Collections -- what are its goals and features? https://github.com/ansible/proposals/issues?q=sort%3Aupdated-desc+collection

**Comment by bcoca** [comment]
Meeting ended Tue May 19 20:11:26 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-19/ansible_core_irc_public_meeting.2020-05-19-19.05.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-19/ansible_core_irc_public_meeting.2020-05-19-19.05.txt
[16:11] <zodbot> Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-19/ansible_core_irc_public_meeting.2020-05-19-19.05.log.html

**Comment by bcoca** [comment]
Meeting ended Thu May 21 16:09:19 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-21/core_public_irc_meeting.2020-05-21-15.12.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-21/core_public_irc_meeting.2020-05-21-15.12.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-21/core_public_irc_meeting.2020-05-21-15.12.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/proposals#178 with implementation ansible/ansible#69680

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69313 (name of changelog generator will change, this is mainly the question whether ansible/ansible is willing to use the new one instead of sticking to the one in ansible/ansible)

**Comment by bcoca** [comment]
Meeting ended Tue May 26 20:10:04 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-26/ansible_core_public_irc_meeting.2020-05-26-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-05-26/ansible_core_public_irc_meeting.2020-05-26-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-05-26/ansible_core_public_irc_meeting.2020-05-26-19.01.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69727 implement remaining missing "deprecation by date" things, make proper deprecation of modules in collections possible (both by date and by version) without adding wrong data or ignoring `ansible-test sanity` errors.

**Comment by felixfontein** [comment]
- [ ] ansible/proposals#178 with implementation ansible/ansible#69680

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69795 ansible-doc: properly handle suboptions
- [ ] ansible/ansible#69796 parse return docs at same place where module docstring is parsed (and tag versions in it). Q: make invalid return YAML also an error, or soft-fail?

**Comment by s-hertel** [comment]
<•zodbot> Limnoria 2019.11.09 Meeting ended Tue Jun  2 20:14:19 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
16:14 Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-02/ansible_core_public_irc_meeting.2020-06-02-19.09.html
16:14 Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-02/ansible_core_public_irc_meeting.2020-06-02-19.09.txt
16:14 Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-02/ansible_core_public_irc_meeting.2020-06-02-19.09.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Jun  4 16:01:14 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-04/core_public_irc_meeting.2020-06-04-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-04/core_public_irc_meeting.2020-06-04-15.02.txt
 Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-04/core_public_irc_meeting.2020-06-04-15.02.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69796 enforce that return value docs are YAML in ansible-doc (like `DOCUMENTATION`)

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69926 Inter-collection deprecation revisited (replace tagged versions/dates with extra fields). Comes with ansible/ansible#69935 to make Ansible 2.9 not crash when modules/plugins use new `AnsibleModule.deprecate`/`Display.deprecated` calls etc.

**Comment by nitzmahone** [comment]
Meeting ended Tue Jun  9 19:57:31 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
12:57 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-09/core_public_irc_meeting.2020-06-09-19.05.html
12:57 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-09/core_public_irc_meeting.2020-06-09-19.05.txt
12:57 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-09/core_public_irc_meeting.2020-06-09-19.05.log.html

**Comment by jamescassell** [comment]
- [ ] separate-filter version of groupdict https://github.com/ansible/ansible/pull/64474

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#69796 resp. the question whether plugin names should be FQCN in the plugin docs
- [ ] ansible/ansible#69742 resp. the question how tombstoning entries in ansible_builtin_runtime.yml / runtime.yml should look like
