### ISSUE TITLE
Public Ansible Project Meeting Agenda - June 2020

### ISSUE THREAD

**Issue by bcoca** [ansible/community#541]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by bcoca** [comment]
Meeting ended Thu Jun  4 16:01:14 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-04/core_public_irc_meeting.2020-06-04-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-04/core_public_irc_meeting.2020-06-04-15.02.txt
 Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-04/core_public_irc_meeting.2020-06-04-15.02.log.html

**Comment by bcoca** [comment]
Meeting ended Tue Jun  9 19:57:31 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
12:57 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-09/core_public_irc_meeting.2020-06-09-19.05.html
12:57 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-09/core_public_irc_meeting.2020-06-09-19.05.txt
12:57 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-09/core_public_irc_meeting.2020-06-09-19.05.log.html

**Comment by bcoca** [comment]
- [ ] separate-filter version of groupdict https://github.com/ansible/ansible/pull/69997 @jamescassel

**Comment by bcoca** [comment]
@felixfontein 
- [ ] ansible/ansible#69796 resp. the question whether plugin names should be FQCN in the plugin docs
- [ ] ansible/ansible#69742 resp. the question how tombstoning entries in ansible_builtin_runtime.yml / runtime.yml should look like

**Comment by jamescassell** [comment]
- [ ] singular `collections_path` https://github.com/ansible/ansible/pull/70007

**Comment by bcoca** [comment]
Meeting ended Thu Jun 11 16:22:38 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-11/ansible_core_public_irc_meeting.2020-06-11-15.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-11/ansible_core_public_irc_meeting.2020-06-11-15.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-11/ansible_core_public_irc_meeting.2020-06-11-15.01.log.html

**Comment by abadger** [comment]
The meeting was ended prematurely.... logs from the continued discussion and agreements:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-11/ansible_core_public_irc_meeting_(part_deux).2020-06-11-16.23.html
10:06:50 
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-11/ansible_core_public_irc_meeting_(part_deux).2020-06-11-16.23.txt
10:06:50 
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-11/ansible_core_public_irc_meeting_(part_deux).2020-06-11-16.23.log.html

**Comment by segal90** [comment]
I would like to attend the next meeting with my PR: https://github.com/ansible/ansible/pull/69801

**Comment by bcoca** [comment]
Meeting ended Tue Jun 23 19:19:21 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-23/ansible_core_public_irc_meeting.2020-06-23-19.09.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-23/ansible_core_public_irc_meeting.2020-06-23-19.09.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-23/ansible_core_public_irc_meeting.2020-06-23-19.09.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#70060 ansible-doc: stop mutating the input in man page formatting
- [ ] ansible/ansible#70026 ansible-doc: include collection name in man page

**Comment by felixfontein** [comment]
- [ ] https://github.com/ansible/ansible/issues/70134#issuecomment-650223767 - how should we fix this?

**Comment by bcoca** [comment]
Meeting ended Tue Jun 30 20:03:37 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-30/ansible_core_public_irc_meeting.2020-06-30-19.01.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-06-30/ansible_core_public_irc_meeting.2020-06-30-19.01.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-06-30/ansible_core_public_irc_meeting.2020-06-30-19.01.log.html
