### ISSUE TITLE
Public Ansible Project Meeting Agenda - Nov/Dec 2020

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#570]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by giner** [comment]
- Minor: Add filter dict, see https://github.com/ansible/ansible/pull/72413
- hosts: reference parent groups from children (makes copy/pastes easy)
- Empty value of `--limit` should raise an error (or at least be no-op)
- Playbooks: Inventory variables should override playbook lever variables by default, see https://github.com/ansible/ansible/issues/63668
- Allow custom success/failure message (should work with no_log: true)
- Roles: A variable should not be passed to a role unless specified in a “spec” file (“defaults” directory could serve this role)

**Comment by nitzmahone** [comment]
* [ ] @nitzmahone update on internal `plugin_utils` discussion

**Comment by Shrews** [comment]
Meeting ended Tue Nov 10 20:00:26 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
3:00 PM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-10/ansible_core_public_irc_meeting.2020-11-10-19.00.html
3:00 PM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-11-10/ansible_core_public_irc_meeting.2020-11-10-19.00.txt
3:00 PM Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-10/ansible_core_public_irc_meeting.2020-11-10-19.00.log.html

**Comment by Shrews** [comment]
Meeting ended Thu Nov 12 15:28:56 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
New messages
10:28 AM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-12/ansible_core_public_irc_meeting.2020-11-12-15.01.html
10:28 AM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-11-12/ansible_core_public_irc_meeting.2020-11-12-15.01.txt
10:28 AM Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-12/ansible_core_public_irc_meeting.2020-11-12-15.01.log.html

**Comment by jamescassell** [comment]
- [ ] python 3.9 builds a wheel before installing the package, so let's be more efficient and just ship a wheel? https://github.com/ansible/ansible/issues/71992#issuecomment-700739135 (issues w/ the upgrade from ansible 2.9 or older)

**Comment by nitzmahone** [comment]
Meeting ended Tue Nov 17 19:11:48 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
11:11 AM Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-17/ansible_core_public_irc_meeting.2020-11-17-19.00.html
11:11 AM Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-11-17/ansible_core_public_irc_meeting.2020-11-17-19.00.txt
11:11 AM Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-17/ansible_core_public_irc_meeting.2020-11-17-19.00.log.html

**Comment by samdoran** [comment]
Meeting ended Thu Nov 19 16:01:19 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-19/ansible_core_public_irc_meeting.2020-11-19-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-11-19/ansible_core_public_irc_meeting.2020-11-19-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-11-19/ansible_core_public_irc_meeting.2020-11-19-15.00.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#72699

**Comment by briantist** [comment]
* [ ]  The `BaseFileCacheModule` (the base class for file-based cache modules) puts out a warning whenever the cache file (which it's about to create for the first time) doesn't exist. There's no way to configure it currently. The warning is not really useful or actionable imo, because again it's just going to get created anyway.

  I think that a non-existent file should be ignored (and in fact in the same class, in the `has_expired` method, that is exactly what is done). Failing that, I think it should be end-user configurable so it can be turned off.

  I'd be happy to take the time to put in a PR for this, but it's core code, in a base class, so I know it's going to have a lot of scrutiny and I want to test the waters before I put that in only to have it closed. So looking for some thoughts from core devs on whether we could change this, preferred way to approach, etc.

  For reference: this is where the warning on a missing file is generated (in the `get` method): https://github.com/ansible/ansible/blob/35022e13a839d5f59a1c4a254aca12afb124373a/lib/ansible/plugins/cache/__init__.py#L170

  This is where the same condition is ignored in `has_expired`: https://github.com/ansible/ansible/blob/35022e13a839d5f59a1c4a254aca12afb124373a/lib/ansible/plugins/cache/__init__.py#L196

**Comment by nitzmahone** [comment]
NOTE: no core meetings week of Nov 23-27 (US holidays)

**Comment by nitzmahone** [comment]
Meeting ended Tue Dec  1 19:22:30 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-01/ansible_core_public_irc_meeting.2020-12-01-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-12-01/ansible_core_public_irc_meeting.2020-12-01-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-01/ansible_core_public_irc_meeting.2020-12-01-19.00.log.html

**Comment by samdoran** [comment]
Meeting ended Thu Dec  3 15:51:20 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-03/ansible_core_public_irc_meeting.2020-12-03-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-12-03/ansible_core_public_irc_meeting.2020-12-03-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-03/ansible_core_public_irc_meeting.2020-12-03-15.00.log.html

**Comment by Nytelife26** [comment]
- [ ] Playbooks / Hostvars: Raw template strings are returned instead of raising an error on hostvars for undefined attribute templates, passing silently instead of failing. For more information see: ansible/ansible#72829

RFC on implementation ideas:
* Include the option as to whether to fail instead of passing silently for unresolvable templates
* Raise a warning / debug message

**Comment by nitzmahone** [comment]
Meeting ended Tue Dec  8 19:29:27 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-08/ansible_core_public_irc_meeting.2020-12-08-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-12-08/ansible_core_public_irc_meeting.2020-12-08-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-08/ansible_core_public_irc_meeting.2020-12-08-19.00.log.html

**Comment by ericzolf** [comment]
* [ ] Add version_sort filter to sort e.g. package lists ansible/ansible#72711

**Comment by mkrizek** [comment]
Meeting ended Thu Dec 10 15:55:28 2020 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-10/ansible_core_public_irc_meeting.2020-12-10-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2020-12-10/ansible_core_public_irc_meeting.2020-12-10-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2020-12-10/ansible_core_public_irc_meeting.2020-12-10-15.00.log.html

**Comment by felixfontein** [comment]
- [ ] ansible/ansible#73010 is there a chance to fix this?

**Comment by sivel** [comment]
- [ ] No core IRC meetings until Jan 5.

**Comment by jerrac** [comment]
Please address the hash_behaviour=merge deprecation issues:
* https://github.com/ansible/ansible/issues/73089
* https://github.com/ansible/ansible/issues/72669
* https://github.com/ansible/ansible/issues/72421
* https://groups.google.com/g/ansible-project/c/9eSApACKTks/m/8ghiXHFHAQAJ

**Comment by bcoca** [comment]
Meeting ended Tue Jan  5 20:02:12 2021 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-05/ansible_core_public_irc_meeting.2021-01-05-19.07.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2021-01-05/ansible_core_public_irc_meeting.2021-01-05-19.07.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2021-01-05/ansible_core_public_irc_meeting.2021-01-05-19.07.log.html
